### ISSUE TITLE
Tool must be run from bin/ directory

### ISSUE THREAD

**Issue by bodaonline** [dvorka/keepass2-to-keepassx#5]
Hi,
I am on ubuntu 14 and trying to convert but get this error:
```
Error: Could not find or load main class com.mindforger.keepass.Keepass2DatabaseToKeepassXDatabase
```
The file named Keepass2DatabaseToKeepassXDatabase.java is in the com/mindforger/keepass folder.
Using JDK7
Thanks, bests

**Comment by dvorka** [comment]
My apologies - start up script is very primitive. Please try to run it from `bin` directory (i.e. `keepass2-to-keepassx.sh` to present in your current directory) and let me know whether it helped. Thanks!

**Comment by bodaonline** [comment]
Hi dvorka,
thanks but still the same err msg comes up :(

**Comment by dvorka** [comment]
Please change to `lib/` directory (where JARs are located) and run the tool directly without script:
```
java -jar keepass2-to-keepassx.jar from.xml to.xml
```

**Comment by bodaonline** [comment]
I have only this is lib/ : xpp3-1.1.4c.jar
Maybe I am missing some files?

**Comment by dvorka** [comment]
Yes, you are missing the main JAR - please download latest release distribution, unzip it and check that there is keepass2-to-keepassx.jar in lib/ directory. Alternatively you may clone Git repo a and build it using Maven.

**Comment by bodaonline** [comment]
I downloaded this: https://github.com/dvorka/keepass2-to-keepassx/archive/1.5.tar.gz
This is what I have. Only one .jar in the lib/

**Comment by dvorka** [comment]
:-Z ... my apologies for wasting so much time - it's really missing there! Please download `ZIP` from the latest release or `tar.gz` that I just added. I really appreciate your feedback and bug report!

**Comment by bodaonline** [comment]
Now it works like a charm! :)) Big thanks for coding this!
